### ISSUE TITLE
what to do when I addAsset

### ISSUE THREAD

**Issue by njacob1001** [CharlesMulloy/epub-builder#12]
hello, when I have book.addAsset("path/.../...");
how I insert for example a image after of paragraph? Is it possible?

**Comment by CharlesMulloy** [comment]
Assume that the asset is going to be right next to the chapter files. For example, if you use

`book.addAsset('path/to/images/puppies.jpeg')`

then your markup should be:

`<img src="puppies.jpeg" />`

Please keep in mind, that the version of epub-builder in npm is not the same as the one here on Github. The Github version allows you to use a second argument in .addAssets() so that you can specify a path in the markup. Look at the [file located here](https://github.com/CharlesMulloy/epub-builder/blob/master/src/testAPI.ts) for some examples.

Please let me know if there is anything else.

**Comment by njacob1001** [comment]
it's posible to integrate this to Reactjs?

**Comment by CharlesMulloy** [comment]
Unfortunately no. Epub-builder is meant to access the disk directly to both get assets and create the epub file properly. 

You might want to look into [JSZip](https://stuk.github.io/jszip/), since epubs are just zip files themselves. If memory serves, I think I've used this project to 'deconstruct' epub files so that the browser can see what is inside of them. If you have a good grasp on how to make an epub programmatically, this is a great tool to use, since it can also create zip files. I've never tried using JSZip with React though, so your millage may vary.
