### ISSUE TITLE
[BUG?] about dcterms:modified meta

### ISSUE THREAD

**Issue by Cologler** [CharlesMulloy/epub-builder#7]
The modified date meta is required on epub 3.1. The epub spec can found here: http://www.idpf.org/epub/31/spec/epub-packages.html#last-modified-date

However the google play book still not support yet. Should we remove it ?

**Comment by CharlesMulloy** [comment]
I would like to include it if possible. Does it completely break compatibility? If not I'll try to include it once I finish the tests I've been working on.

**Comment by Cologler** [comment]
Yes, I think so. Before remove the metadata, google play book does not accept the epub file.

**Comment by CharlesMulloy** [comment]
That's unfortunate. Do you know of anything else that this breaks besides Google Books? If the list isn't long, then it might be a good idea to put in the API a chance to override the inclusion/exclusion of the meta, depending on what default we decide to go with.

An argument for setting the default to include is we'd be following the specifications more closely. An argument against including is that we'd be maintaining compatibility (specifically with Google Books). Quite a dilemma, but I'm leaning towards the former (including by default) since only one application is being broken (that we know of). The project might also be missing something else that is breaking the compatibility with Google Books too and this bug will go away entirely when we find it.

**Comment by Cologler** [comment]
Here are epub check result:

``` 
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): Error while parsing file 'attribute "property" not allowed here; expected attribute "content", "id", "name", "scheme" or "xml:lang"'.
ERROR(RSC-005): Error while parsing file 'element "meta" missing required attributes "content" and "name"'.
```

Seems epub 3.1 break some rules in epub 2.0.1.
